[package]
name = "sequencer"
version = "0.1.0"
edition = "2024"

[dependencies]
compiler = { path = "../compiler" }
curvevm = { path = "../curvevm" }
hotshot = { path = "../hotshot" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
