[package]
name = "sequencer"
version = "0.1.0"
edition = "2024"

[dependencies]
compiler = { path = "../compiler" }
curvevm = { path = "../curvevm" }
hotshot = { path = "../hotshot" }
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
