name: Rust tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Build and test workspace
      run: cargo test --workspace --all-targets
    - name: Run Hotshot tests
      run: cargo test -p hotshot
